<?php
/**
 * Created by PhpStorm.
 * User: nikitaignatenkov
 * Date: 18/06/2018
 * Time: 23:25
 */

namespace ignatenkovnikita\defcode\console;


use ignatenkovnikita\csv\CsvImporter;
use ignatenkovnikita\csv\CsvReader;
use ignatenkovnikita\defcode\components\MnpImporter;
use yii\console\Controller;

class MnpController extends Controller
{

    public $basePath;

    public function init()
    {
        $this->basePath = \Yii::getAlias('@console/runtime/');

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionDownload($url)
    {
        $name = 'mnp';
        $fileName = $this->basePath . $name . '.csv';
        $this->log('download ' . $fileName);
        if (file_exists($fileName)) {
            $newFileName = $this->basePath . $name . '_' . date('Y-m-d-H-i-s', filemtime($fileName)) . '.csv';
            rename($fileName, $newFileName);
        }
        file_put_contents($fileName, fopen($url, 'r'));


    }


    public function actionImport()
    {
        ini_set('memory_limit', '-1');
        $time = microtime(true);


        $fileName = $this->basePath . 'mnp.csv';
        if (file_exists($fileName) && filesize($fileName)) {
            $this->log('start file ' . $fileName . ', type ' . $type);

            $importer = new CsvImporter();
            $importer->setData(new CsvReader([
                'filename' => $fileName,
                'fgetcsvOptions' => [
//                'delimiter' => '\n'
                ],
                'startFromLine' => 1
            ]));
            $importerClass = new MnpImporter();
            $r = $importer->import($importerClass, []);
            $this->log($r);
            $this->log('end file ' . $fileName . ', type ' . $type);
        } else {
            $this->log('not correct file ' . $fileName);
        }
        $this->log('done (time: ' . sprintf('%.3f', microtime(true) - $time) . "s)\n");

    }


    protected function log($text)
    {
        echo date('Y-m-d H:i:s') . ' ' . $text . PHP_EOL;
    }
}